import uuid
from typing import List, Optional
from src.llm_client import LLMClient
from src.models import MCQQuestion, FreeformQuestion, Question, QuestionType
from src.prompts import QUESTION_GENERATION_SYSTEM_PROMPT
from pydantic import BaseModel, Field

class LLMQuestion(BaseModel):
    """Schema for a single question generated by the LLM."""
    type: str = Field(description="Must be 'multiple_choice' or 'freeform'")
    text: str
    correct_answer: str
    options: Optional[List[str]] = Field(default=None, description="Required only for MCQ")

class LLMQuestionList(BaseModel):
    """Schema for a list of generated questions."""
    questions: List[LLMQuestion]

class QuestionGenerator:
    """Handles the generation of questions using OpenAI Structured Outputs."""

    def __init__(self, llm_client: LLMClient) -> None:
        self.llm_client = llm_client

    def generate_questions(self, topic: str, count: int = 5) -> List[Question]:
        """Generate validated questions using the structured response model."""
        prompt = f"Generate {count} high-quality questions about '{topic}'. Include a mix of MCQ and freeform."
        
        parsed_data = self.llm_client.generate_structured_response(
            prompt, 
            LLMQuestionList, 
            QUESTION_GENERATION_SYSTEM_PROMPT
        )
        
        if not parsed_data:
            return []
            
        return self._convert_to_domain_models(parsed_data.questions, topic)

    @staticmethod
    def _convert_to_domain_models(llm_questions: List[LLMQuestion], topic: str) -> List[Question]:
        """Transform Pydantic models into internal domain Question objects."""
        domain_questions: List[Question] = []
        for q in llm_questions:
            q_id = str(uuid.uuid4())[:8]
            if q.type == QuestionType.MCQ.value:
                domain_questions.append(MCQQuestion(
                    question_id=q_id, topic=topic, text=q.text,
                    correct_answer=q.correct_answer, options=q.options or []
                ))
            else:
                domain_questions.append(FreeformQuestion(
                    question_id=q_id, topic=topic, text=q.text, correct_answer=q.correct_answer
                ))
        return domain_questions